name: Write updated Token List

on:
  push: {}
  workflow_dispatch: {}
  schedule:
    - cron: "0 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn
      - name: Install Husky
        run: yarn install-husky
      - name: Update Token List and commit
        run: "git config --global user.name '${{github.actor}}' && \
              git config --global user.email '${{github.actor}}@users.noreply.github.com' && \
              (git commit -a -m 'Updated Token List' || true) && \
              git push -u origin HEAD"