name: Write updated Token List

on:
  push:
  schedule:
    - cron: "0 */2 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn
      - name: Update Token List
        run: yarn write
      - name: Commit updated Token List
        run: "git config --global user.name '${GITHUB_ACTOR}' && \
              git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com' && \
              git add -A && git commit -m 'Updated Token List' && \
              git push -u origin HEAD"